// <auto-generated />
using System;
using HealthBridgeAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HealthBridgeAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HealthBridgeAPI.Models.Entities.Appointment", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppointmentId"));

                    b.Property<string>("AppointmentCancellationReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AppointmentComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AppointmentDateTimeCreated")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AppointmentDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AppointmentEndDateTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AppointmentMinutesDuration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AppointmentParticipantPatientId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AppointmentParticipantPractitionerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AppointmentReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AppointmentStartDateTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AppointmentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AppointmentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.HasKey("AppointmentId");

                    b.HasIndex("LocationId");

                    b.HasIndex("PatientId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("HealthBridgeAPI.Models.Entities.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocationId"));

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LocationId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("HealthBridgeAPI.Models.Entities.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientId"));

                    b.Property<string>("PatientAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PatientBirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PatientComunicationLanguagePreference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PatientDeceased")
                        .HasColumnType("bit");

                    b.Property<string>("PatientEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatientEmergencyContactPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatientEthnicity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatientExtensionRace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatientFirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatientGender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatientGeneralPractitioner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatientGeneralPractitionerExtensionDateLastSeen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatientHomePhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatientLastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatientMaritalStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatientMobilePhone")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PatientPMS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatientReferralResource")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatientSSN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatientStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatientWorkPhone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PatientId");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("HealthBridgeAPI.Models.Entities.Practitioner", b =>
                {
                    b.Property<int>("PractitionerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PractitionerId"));

                    b.Property<long>("PractitionerIdentifier")
                        .HasColumnType("bigint");

                    b.Property<string>("PractitionerLastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PractitionerLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PractitionerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("PractitionerOnLine")
                        .HasColumnType("bit");

                    b.Property<string>("PractitionerPhotoRef")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PractitionerProvider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PractitionerSpecialty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PractitionerStatus")
                        .HasColumnType("bit");

                    b.HasKey("PractitionerId");

                    b.ToTable("Practitioners");
                });

            modelBuilder.Entity("HealthBridgeAPI.Models.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("UserCreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserFailedAttempts")
                        .HasColumnType("int");

                    b.Property<bool>("UserIsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UserLastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UserLockoutUntil")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("UserOrganizationId")
                        .HasColumnType("int");

                    b.Property<string>("UserPasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserPasswordSalt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HealthBridgeAPI.Models.Entities.Appointment", b =>
                {
                    b.HasOne("HealthBridgeAPI.Models.Entities.Location", "Locations")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthBridgeAPI.Models.Entities.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Locations");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HealthBridgeAPI.Models.Entities.Patient", b =>
                {
                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
